site_name: typed-ffmpeg
site_description: Data validation using Python type hints
strict: true
site_url: https://livingbio.github.io/typed-ffmpeg/

theme:
  name: "material"

repo_name: livingbio/typed-ffmpeg
repo_url: https://github.com/livingbio/typed-ffmpeg
edit_uri: edit/main/docs/
extra:
  version:
    provider: mike

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

markdown_extensions:
- tables
- toc:
    permalink: true
    title: Page contents
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.extra
- pymdownx.tabbed:
    alternate_style: true

watch:
- src

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google
          docstring_section_style: table
          show_root_heading: true
          extensions:
            - griffe_inherited_docstrings
